spring:
    datasource:
        url: "jdbc:h2:mem:testDB"
        username: bo
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    h2:
        console:
            enabled: true
            path: "/h2-console"
