spring:
    datasource:
        url: "jdbc:h2:mem:testDB;MODE=MySQL"
        username: bo
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
    h2:
        console:
            enabled: true
            path: "/h2-console"
